# -*- coding: utf-8 -*-
"""Lab2Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FPV5MXAts68TSy30_NrFyU139l6ZsPoK
"""



"""Matplotlib

Numpy

Dictionary

List

Tuple

Set
"""

Num=[1,2,3,4,5,6,7,8,9,10]
print(Num)

print("Max:", max(Num))

print("Sum is:", sum(Num) )

print("Min:", min(Num))

Num.append(11)
print("list after append:", Num)

Num.remove(9)
print("List After remove:", Num)

print("List After reverse:", sorted(Num, reverse=True))

fruit_tuple = ('Apples', 'Banana', 'Orange', 'Apricot', 'Mango')
print(fruit_tuple)
print(fruit_tuple[1])
print(fruit_tuple[4])

fruits_list = list(fruit_tuple)
fruits_list[3] = 'Pear'
print("Modified List:", fruits_list)

setA = {1, 2, 3, 4, 5}
setB = {2, 3, 4, 5, 6}
print("Set A:", setA)
print("Set B:", setB)

print("Union:", setA | setB)

print("Intersection:", setA & setB)

print("Difference (A - B):", setA - setB)

print("Symmetric Difference:", setA ^ setB)

my_dict = {"name": "Farhan",
           "age": 22,
           "city": "Swat"}


print(my_dict["name"])
print(my_dict)

my_dict["email"] = "Farhan@example.com"
my_dict["age"] = 23


del my_dict["city"]

print(my_dict)